export default {
  menuList: [{
      menuLcl: 'NOTICE',
      index: 1,
      menuNm: '공지사항 조회',
      url: 'noticeMain',
    },
    {
      menuLcl: 'IFREG',
      index: 1,
      menuNm: 'I/F 신청서',
      url: 'applyIf',
    },
    {
      menuLcl: 'IFREG',
      index: 2,
      menuNm: 'I/F 정보 변경 요청서',
      url: 'chgIfinfo',
    },
    {
      menuLcl: 'IFREGLIST',
      index: 1,
      menuNm: '신청목록',
      url: 'regList',
    },
    {
      menuLcl: 'META_ALL',
      index: 1,
      menuNm: 'EIGW',
      url: 'eigwOnlineList',
    },
    {
      menuLcl: 'META_ALL',
      index: 2,
      menuNm: 'MCG',
      url: 'mcgDtlList',
    },
    {
      menuLcl: 'META_ALL',
      index: 3,
      menuNm: 'EAI',
      url: 'queueList',
    },
    {
      menuLcl: 'META_EIGW',
      index: 1,
      menuNm: '온라인 리스트',
      url: 'eigwOnlineList',
    },
    {
      menuLcl: 'META_EIGW',
      index: 2,
      menuNm: '메타정보',
      url: 'eigwFileList',
    },
    {
      menuLcl: 'META_MCG',
      index: 1,
      menuNm: '채널 조회',
      url: 'mcgDtlList',
    },
    {
      menuLcl: 'META_MCG',
      index: 2,
      menuNm: '거래 조회',
      url: 'mcgTransInfo',
    },
    {
      menuLcl: 'META_EAI',
      index: 1,
      menuNm: '큐 목록',
      url: 'queueList',
    },
    {
      menuLcl: 'META_EAI',
      index: 2,
      menuNm: '큐 매니저 목록',
      url: 'queueMgrList',
    },
    {
      menuLcl: 'META_EAI',
      index: 3,
      menuNm: '채널 목록',
      url: 'chnList',
    },
    {
      menuLcl: 'META_EAI',
      index: 4,
      menuNm: '노드 매니저 목록',
      url: 'nodeList',
    },
    {
      menuLcl: 'META_EAI',
      index: 5,
      menuNm: 'SWING DB 정보',
      url: 'swingDbInfo',
    },
    {
      menuLcl: 'META',
      index: 1,
      menuNm: 'EIGW',
      url: 'aeigwOnlineListaa',
    },
    {
      menuLcl: 'META',
      index: 2,
      menuNm: 'MCG',
      url: 'mcgDtlList',
    },
    {
      menuLcl: 'META',
      index: 3,
      menuNm: 'EAI',
      url: 'queueList',
    },
    {
      menuLcl: 'MGMT_COMM',
      index: 1,
      menuNm: '공통 코드 관리',
      url: 'ccCdList',
    },
    {
      menuLcl: 'MGMT_COMM',
      index: 2,
      menuNm: '서버 정보 관리',
      url: 'serverList',
    },
    {
      menuLcl: 'MGMT_COMM',
      index: 3,
      menuNm: '기관 코드 관리',
      url: 'instList',
    },
    {
      menuLcl: 'MGMT_EIGW',
      index: 1,
      menuNm: '프로그램 관리',
      url: 'programInfo',
    },
    {
      menuLcl: 'MGMT_EIGW',
      index: 2,
      menuNm: '대외 담당자 관리',
      url: 'accListEigw',
    },
    {
      menuLcl: 'MGMT_EIGW',
      index: 3,
      menuNm: '대외기관서버 관리',
      url: 'eigwServer',
    },
    {
      menuLcl: 'MGMT_EIGW',
      index: 4,
      menuNm: '메타정보',
      url: 'fileListAdmin',
    },
    {
      menuLcl: 'MGMT_EIGW',
      index: 5,
      menuNm: '메타정보(실시간)',
      url: 'onlineListAdmin',
    },
    {
      menuLcl: 'MGMT_MCG',
      index: 1,
      menuNm: '가상사용자 관리',
      url: 'virtualUserList_MCG',
    },
    {
      menuLcl: 'MGMT_MCG',
      index: 2,
      menuNm: '담당자 관리',
      url: 'mcgChrgr',
    },
    {
      menuLcl: 'MGMT_MCG',
      index: 3,
      menuNm: '서버 관리',
      url: 'mcgServer',
    },
    {
      menuLcl: 'MGMT_EAI',
      index: 1,
      menuNm: 'EAI 승인 완료 목록',
      url: 'approEaiList',
    },
  ],
};
